"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z4+3tbtew^^h$h^_u&2o1=$_+d0&yt2dy)2az0vwxkd65mrj*z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.import_export",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'import_export',
    'front', 
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz-uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ═══════════════════════════════════════════════════════════════
# UNFOLD CONFIGURATION
# ═══════════════════════════════════════════════════════════════

from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "PolyglotLC",
    "SITE_HEADER": "PolyglotLC Admin",
    "SITE_URL": "/",
    "SITE_SYMBOL": "school",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
    },
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Asosiy",
                "separator": True,
                "items": [
                    {"title": "Dashboard", "icon": "dashboard", "link": reverse_lazy("admin:index")},
                    {"title": "Sayt sozlamalari", "icon": "settings", "link": reverse_lazy("admin:front_sitesettings_changelist")},
                ],
            },
            {
                "title": "Ta'lim",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Kurslar", "icon": "school", "link": reverse_lazy("admin:front_course_changelist")},
                    {"title": "Fanlar", "icon": "category", "link": reverse_lazy("admin:front_subject_changelist")},
                    {"title": "O'qituvchilar", "icon": "people", "link": reverse_lazy("admin:front_teacher_changelist")},
                    {"title": "Sertifikatlar", "icon": "workspace_premium", "link": reverse_lazy("admin:front_certificate_changelist")},
                ],
            },
            {
                "title": "Arizalar",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Kursga yozilishlar", 
                        "icon": "how_to_reg", 
                        "link": reverse_lazy("admin:front_courseenrollment_changelist"),
                        "badge": "front.utils.get_pending_enrollments"
                    },
                    {
                        "title": "O'qituvchi arizalari", 
                        "icon": "person_add", 
                        "link": reverse_lazy("admin:front_teacherapplication_changelist"),
                        "badge": "front.utils.get_pending_applications"
                    },
                    {
                        "title": "Xabarlar", 
                        "icon": "mail", 
                        "link": reverse_lazy("admin:front_contact_changelist"),
                        "badge": "front.utils.get_new_messages"
                    },
                ],
            },
            {
                "title": "Kontent",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Yangiliklar", "icon": "newspaper", "link": reverse_lazy("admin:front_news_changelist")},
                    {"title": "Sharhlar", "icon": "reviews", "link": reverse_lazy("admin:front_testimonial_changelist")},
                    {"title": "Galereya", "icon": "photo_library", "link": reverse_lazy("admin:front_gallery_changelist")},
                    {"title": "Galereya kategoriyalari", "icon": "folder", "link": reverse_lazy("admin:front_gallerycategory_changelist")},
                    {"title": "FAQ", "icon": "help", "link": reverse_lazy("admin:front_faq_changelist")},
                    {"title": "FAQ kategoriyalari", "icon": "folder", "link": reverse_lazy("admin:front_faqcategory_changelist")},
                ],
            },
            {
                "title": "Tizim",
                "separator": True,
                "collapsible": True,
                "items": [
                    {"title": "Foydalanuvchilar", "icon": "person", "link": reverse_lazy("admin:front_user_changelist")},
                    {"title": "Guruhlar", "icon": "groups", "link": reverse_lazy("admin:auth_group_changelist")},
                ],
            },
        ],
    },
}

IMPORT_EXPORT_USE_TRANSACTIONS = True

